// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlvnnkzdqlnvxomucwfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsdm5ua3pkcWxudnhvbXVjd2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDQwMzAsImV4cCI6MjA2OTcyMDAzMH0.7-uCjZOALqHVOd3HP22rjlgVFSNIo1oz3zzZ1JXuPIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});